### ISSUE TITLE
Comment between tasklists causes error

### ISSUE THREAD

**Issue by C-h-r-i-s** [docmalloc/gplmt#17]
Inserting a comment in between of two tasklists causes the following error 
...
</tasklist>

<tasklist name=...

Traceback (most recent call last):
  File "gplmt-light.py", line 54, in <module>
    experiment = Experiment.from_file(args.experiment_file, settings=args)
  File "/usr/share/gplmt-new/gplmtlib.py", line 72, in from_file
    process_includes(document, parent_filename=filename)
  File "/usr/share/gplmt-new/gplmtlib.py", line 948, in process_includes
    augment_experiment(experiment_xml, extension_xml, prefix)
  File "/usr/share/gplmt-new/gplmtlib.py", line 914, in augment_experiment
    t.set('name', "{0}.{1}".format(prefix, t.get('name', '_unknown')))
  File "lxml.etree.pyx", line 1548, in lxml.etree.__ContentOnlyElement.set (src/lxml/lxml.etree.c:51108)
  File "lxml.etree.pyx", line 1544, in lxml.etree.__ContentOnlyElement._raiseImmutable (src/lxml/lxml.etree.c:51004)
TypeError: this element does not have children or attributes

**Comment by FlorianDold** [comment]
Should work now, comments are stripped.
