### ISSUE TITLE
Using register-teardown step causes error 

### ISSUE THREAD

**Issue by C-h-r-i-s** [docmalloc/gplmt#18]
Traceback (most recent call last):
  File "gplmt-light.py", line 55, in <module>
    experiment.run_synchronous()
  File "/usr/share/gplmt-new/gplmtlib.py", line 96, in run_synchronous
    loop.run_until_complete(self._run())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 302, in _step
    result = next(coro)
  File "/usr/share/gplmt-new/gplmtlib.py", line 81, in _run
    yield from testbed.run_step(step, self.tasklists_env)
  File "/usr/share/gplmt-new/gplmtlib.py", line 429, in run_step
    yield from self.ec.run_step(step_xml, tasklists_env)
  File "/usr/share/gplmt-new/gplmtlib.py", line 205, in run_step
    yield from step_method(self, step_xml, tasklists_env)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 84, in coro
    res = func(_args, *_kw)
  File "/usr/share/gplmt-new/gplmtlib.py", line 248, in _step_teardown
    self.teardowns.append((targets_def, tasklist))
AttributeError: 'ExecutionContext' object has no attribute 'teardowns'

**Comment by FlorianDold** [comment]
Should be fixed now.
