### ISSUE TITLE
Using seq in tasklist causes error

### ISSUE THREAD

**Issue by C-h-r-i-s** [docmalloc/gplmt#21]
using tasklist like:  
<tasklists>
    <tasklist name="ping">
      <seq>
       <run>ping -c 10 8.8.8.8</run>
      </seq>
   </tasklist>
 </tasklists>

Causes:
2015-11-11 16:06:47 CET gplmtlib INFO running tasklist 'ping'
2015-11-11 16:06:47 CET gplmtlib INFO Running tasklist ping with timeout of None.
2015-11-11 16:06:47 CET gplmtlib INFO 1 tasks done, 0 task pending
Traceback (most recent call last):
  File "gplmt-light.py", line 55, in <module>
    experiment.run_synchronous()
  File "/usr/share/gplmt-new/gplmtlib.py", line 99, in run_synchronous
    loop.run_until_complete(self._run())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
    result = coro.send(value)
  File "/usr/share/gplmt-new/gplmtlib.py", line 85, in _run
    yield from testbed.join()
  File "/usr/share/gplmt-new/gplmtlib.py", line 435, in join
    yield from self.ec.join(targets)
  File "/usr/share/gplmt-new/gplmtlib.py", line 135, in join
    task.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 298, in _step
    result = coro.throw(exc)
  File "/usr/share/gplmt-new/gplmtlib.py", line 598, in run_tasklist
    yield from asyncio.wait_for(asyncio.async(coro), timeout)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 421, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.4/asyncio/futures.py", line 348, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 351, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 302, in _step
    result = next(coro)
  File "/usr/share/gplmt-new/gplmtlib.py", line 546, in _run_list
    yield from self._run_task(task_xml, testbed, tasklists_env)
  File "/usr/share/gplmt-new/gplmtlib.py", line 652, in _run_task
    for child_task in task:
UnboundLocalError: local variable 'task' referenced before assignment

**Comment by FlorianDold** [comment]
Fixed in 9620982...
